# This is a sample build configuration for Java (Gradle).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: openjdk:8

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - chmod +x gradlew
          - bash ./gradlew build
          
          - pipe: atlassian/firebase-deploy:0.3.6
            variables:
              FIREBASE_TOKEN: '1//09Mn5enO60JRPCgYIARAAGAkSNwF-L9IriSjfTm3eC2Z3C3QEk_aymxJNGyIK7jegzFPgw9DvpuTt2--Ua6biD_BwBUpmMi7v_ms'
              PROJECT_ID: 'VITTLES_ALPHA01'

