package com.example.vittles.productlist

import com.example.vittles.di.AppComponent
import com.example.vittles.di.ApplicationScope
import dagger.Component

/**
 * Component for main product injections.
 *
 * @author Jeroen Flietstra
 * @author Arjen Simons
 */
@ApplicationScope
@Component(modules = [ProductsModule::class],
        dependencies = [AppComponent::class]
)
interface ProductsComponent {
    /**
     * Generated by Dagger framework.
     *
     * @param view The ProductActivity that needs injection.
     */
    fun inject(view: ProductsActivity)
}