package com.example.vittles.di

import android.app.Application
import android.content.Context
import dagger.Module
import dagger.Provides
import javax.inject.Singleton

/**
 * Main application module for dependency injections.
 *
 * @author Jeroen Flietstra
 * @author Arjen Simons
 */
@Module(includes = [AppDbModule::class])
class AppModule {

    /**
     * Provides the application context as injection. Generated by Dagger framework.
     *
     * @param application The application of Vittles.
     * @return The application context of the application.
     */
    @Singleton
    @Provides
    fun provideContext(application: Application): Context = application.applicationContext
}

/*
@Module and @Provides: define classes and methods which provide dependencies.
 */