package com.example.vittles.productadd

import com.example.vittles.di.AppComponent
import com.example.vittles.di.ApplicationScope
import dagger.Component

/**
 * Component for AddProduct injections.
 *
 * @author Jeroen Flietstra
 * @author Arjen Simons
 */
@ApplicationScope
@Component(modules = [AddProductModule::class],
    dependencies = [AppComponent::class]
)
interface AddProductComponent {
    /**
     * Generated by Dagger framework.
     *
     * @param view The AddProductActivity that needs injection.
     */
    fun inject(view: AddProductActivity)
}