package com.example.vittles.services.notification

import com.example.domain.productfetch.FetchProductsUseCase
import com.example.domain.repositories.ProductsRepository
import dagger.Module
import dagger.Provides

/**
 * Module for AddProduct dependency injections.
 *
 * @author Jeroen Flietstra
 * @author Arjen Simons
 */
@Module
class NotificationModule {

    /**
     * Provides the AddProductUseCase as injection. Generated by Dagger framework.
     *
     * @param productsRepository ProductsRepository needed for the AddProductUseCase.
     */
    @Provides
    fun provideAuditNotificationUseCase(productsRepository: ProductsRepository) = FetchProductsUseCase(productsRepository)
}